### ISSUE TITLE
Untranslatable texts

### ISSUE THREAD

**Issue by christof337** [dyslexic-charactersheets/translator#1]
Hi

In the french character 

- [x] sheet, 2nd page, under `Armour class` (`Classe d'armure` in french), there is an untranslatable text : "Armour Potency". I cannot find it in the translation platform (neither under potency nor armour/armor).

Is it hard coded? Could you extract it so that it appears in the translation platform for me to translate it please?
Thanks !
 ![armour_potency](https://github.com/dyslexic-charactersheets/translator/assets/4980937/3cad4264-2939-428f-9510-bbfe8239c58f)

- [x] Same goes for "Can't step into difficult terrain" in the actions page

![step](https://github.com/dyslexic-charactersheets/translator/assets/4980937/96d39911-ca31-46e3-b03f-c76d4cb6ad06)
same page : crawl and 

- [x] drop prone

![crawl](https://github.com/dyslexic-charactersheets/translator/assets/4980937/4e29b679-b651-4f7b-b2e3-51f383d9c5aa)

idem for circled text 

- [ ] : Spell Level, Spells per day, and Spell today

![spells](https://github.com/dyslexic-charactersheets/translator/assets/4980937/91c1ef54-82f9-404b-b0ed-8bbbffd73738)

- [ ] : 
![IMG_20240117_082720](https://github.com/dyslexic-charactersheets/translator/assets/4980937/92c86f76-128f-4bea-8c64-0e8c18a9ea70)

**Comment by marcus-downing** [comment]
Sorry for the delay.
Translation lists have been updated.
