### ISSUE TITLE
[PF2] Typos found in the translation platform

### ISSUE THREAD

**Issue by christof337** [dyslexic-charactersheets/translator#2]
- [ ] Archetype sentinel  : Whenever you gain a class feature that improves your proficiency in a given **weapon**, also gain that proficiency in these armour types. --> should be **armor/armour**
- [ ] archetype sentinel : Whenever you gain a class feature that grants you expert **prorficiency** in unarmoured defence, also become expert in these armour types. --> should be **proficiency**

**Comment by marcus-downing** [comment]
1. I use British spelling.
2. Yep, that's a typo.

**Comment by christof337** [comment]
Sorry, I got no problem with british spelling 🤗
It IS your proficiency in a given **ARMOUR** that gives you proficiency with these armour types.
Previously it was
your proficiency in a given **WEAPON** gives you proficiency with these armour types.
(I updated accordingly)
