### ISSUE TITLE
Few typos

### ISSUE THREAD

**Issue by christof337** [dyslexic-charactersheets/translator#6]
Please find below a few typos I found while translating

- [ ] if trained, it's only up to 2nd level (pre remaster)
![Screenshot_2024-02-21-11-42-09-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dyslexic-charactersheets/translator/assets/4980937/6ae87914-bfb6-45d4-b246-4418f08ca388)

- [ ] unseen servant**y**
![Screenshot_2024-02-21-11-40-48-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dyslexic-charactersheets/translator/assets/4980937/48205b03-c002-45e4-a99d-26d39c7a601f)

- [ ] advanced player guide**r**
![Screenshot_2024-02-20-11-37-21-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dyslexic-charactersheets/translator/assets/4980937/69e9ad6d-e036-4652-aed4-9123df87bb28)

- [ ] fascinating performance 
![Screenshot_2024-02-21-14-23-46-38_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dyslexic-charactersheets/translator/assets/4980937/07aaff13-8fe7-454a-a67b-eee65e670203)

- [ ] Surival
![Screenshot_2024-02-21-14-42-21-72_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dyslexic-charactersheets/translator/assets/4980937/2bc854b3-c0b6-4b01-aca7-b133ff365449)

- [ ] should be 40ft
![Screenshot_2024-02-21-14-44-24-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dyslexic-charactersheets/translator/assets/4980937/4eb05767-f4cd-4b7b-8750-2edb47c43957)

**Comment by marcus-downing** [comment]
Thanks, I've fixed these.
The fix won't show up on the translators site until I next do an update.
